volumes:
  db-data:

services:
  db:
    # Pinning MariaDB to point release 10.4.30 works around the issues with the
    # database migrations seen with 10.4.31 in issue https://github.com/steve-community/steve/issues/1212.
    #
    # TODO: Get database migrations to work with the latest point releases of
    # MariaDB 10.4.
    image: mariadb:10.4.30
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: stevedb
      MYSQL_USER: steve
      MYSQL_PASSWORD: changeme
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
      args:
        DB_HOST: host.docker.internal
        DB_PORT: 3306
        DB_DATABASE: stevedb
        DB_USER: steve
        DB_PASSWORD: changeme
    image: steve:test
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code
    ports:
      - "8180:8180"
      - "8443:8443"

