name: build and run tests
on: [ push, pull_request ]

env:
  DB_SCHEMA: stevedb_test_2aa6a783d47d
  DB_USER: steve
  DB_PASSWORD: changeme

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-24.04 ]
        java: [ '21', '24' ]
        db: [ 'mysql:8.0', 'mariadb:10.3', 'mariadb:10.4.30', 'mariadb:10.5.21', 'mariadb:10.6.14' ]
    runs-on: ${{ matrix.os }}
    services:
      mysql:
        image: ${{ matrix.db }}
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: root
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v5
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven

      - name: Set up MySQL
        run: |
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "SELECT @@VERSION;"
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "CREATE DATABASE $DB_SCHEMA;" -v
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';" -v
          mysql -h 127.0.0.1 -P 3306 -uroot -proot -e "GRANT ALL PRIVILEGES ON $DB_SCHEMA.* TO '$DB_USER'@'%';" -v

      - name: Build with Maven
        run: |
          ./mvnw -B -V \
            -Pdev,useRealDatabase \
            -DskipTests=false \
            -Dmaven.javadoc.skip=true \
            -Ddb.jdbc.url="jdbc:mysql://127.0.0.1:3306/${DB_SCHEMA}?sslMode=PREFERRED&serverTimezone=UTC" \
            -Ddb.schema="${DB_SCHEMA}" \
            -Ddb.user="${DB_USER}" \
            -Ddb.password="${DB_PASSWORD}" \
            -Ddb.sql.logging=true \
            -Dprofile=test \
            -Dappender=CONSOLE \
            clean package --file pom.xml

      - name: Start the app and visit signin web page
        run: |
          sudo apt-get install -y elinks
          java -Djava.net.preferIPv4Stack=true -jar steve/target/steve.jar &
          sleep 30
          elinks -dump -no-references http://localhost:8080/manager/signin
          killall java
