name: analyze and review code
on: [ push, pull_request ]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Check license headers
        run: ./mvnw -B -V com.mycila:license-maven-plugin:5.0.0:check
  style-check:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check code style
        run: ./mvnw spotless:check
